import { randomUUID } from 'node:crypto';
import { encryptBallot, voteHash } from '../../../packages/crypto/src/index.js';
import type { CouchClient } from '../../../packages/couchdb/src/client.js';
import type { Ledger } from '../../../packages/ledger/src/index.js';
import type { Candidate, VoteDoc, VoteProof } from '../../../packages/shared/src/types.js';
export class ElectionService {
 constructor(private couch:CouchClient,private ledger:Ledger,private key:Buffer,private electionId:string,private district:string){}
 async castVote(voterId:string,candidate:Candidate){const t0=performance.now();const voter=await this.couch.voters().get(voterId);const authMs=performance.now()-t0;if(!voter)throw new Error('ERR_VOTER_NOT_FOUND');if(voter.district!==this.district)throw new Error('ERR_INVALID_DISTRICT');if(voter.isVoted)throw new Error('ERR_ALREADY_VOTED');
 const voteDocId=randomUUID(),te=performance.now(),encryptedBallot=encryptBallot(candidate,this.key),encryptionMs=performance.now()-te; let claimed;try{claimed=await this.couch.voters().put({...voter,isVoted:true,voteDocId,voteState:'PENDING_PROOF'})}catch(e){if((e as any).status===409)throw new Error('ERR_CONCURRENT_VOTE_CONFLICT');throw e}
 const doc:VoteDoc={_id:voteDocId,voteDocId,encryptedBallot,district:this.district,electionId:this.electionId,timestamp:new Date().toISOString()};const td=performance.now();const stored=await this.couch.votes().put(doc);const couchInsertMs=performance.now()-td;const th=performance.now();const hash=voteHash(encryptedBallot);const hashMs=performance.now()-th;const proof:VoteProof={voteDocId,voteDocRev:stored._rev!,voteHash:hash,district:this.district,electionId:this.electionId,timestamp:doc.timestamp};const tl=performance.now();const committed=await this.ledger.submitVoteProof(proof,'vote-submitter');const proofCommitMs=performance.now()-tl;await this.couch.voters().put({...claimed,voteState:'VOTE_COMPLETE'});return{voteDocId,revision:stored._rev,transactionId:committed.transactionId,timings:{authenticationMs:authMs,encryptionMs,couchInsertMs,hashMs,proofCommitMs,endToEndMs:performance.now()-t0}}}
 async retryPendingProof(voterId:string){const voter=await this.couch.voters().get(voterId);if(!voter?.voteDocId||voter.voteState!=='PENDING_PROOF')throw new Error('ERR_NO_PENDING_PROOF');const existing=await this.ledger.getVoteProof(voter.voteDocId);if(existing){await this.couch.voters().put({...voter,voteState:'VOTE_COMPLETE'});return existing}const doc=await this.couch.votes().get(voter.voteDocId);if(!doc?._rev)throw new Error('ERR_PENDING_VOTE_MISSING');const proof={voteDocId:doc.voteDocId,voteDocRev:doc._rev,voteHash:voteHash(doc.encryptedBallot),district:doc.district,electionId:doc.electionId,timestamp:doc.timestamp};const out=await this.ledger.submitVoteProof(proof,'vote-submitter');await this.couch.voters().put({...voter,voteState:'VOTE_COMPLETE'});return out}
}
