#!/bin/bash
# verify-network.sh
# Network verification commands for the 4-Orderer BFT network

set -e

echo "=========================================="
echo "  Network Verification Commands"
echo "=========================================="

echo -e "\n${YELLOW}[1] Check Orderer Status${NC}"
echo "------------------------------------------"
echo "# Check if orderers are running:"
echo "docker ps | grep orderer"
echo ""
echo "# Verify orderer logs:"
echo "docker logs orderer1.example.com 2>&1 | tail -20"
echo ""
echo "# Check orderer health:"
echo "curl -k https://orderer1.example.com:8443/health 2>/dev/null || echo 'Health endpoint not available'"

echo -e "\n${YELLOW}[2] Check Peer Status${NC}"
echo "------------------------------------------"
echo "# Check if peers are running:"
echo "docker ps | grep peer"
echo ""
echo "# Verify peer joined channel:"
echo "docker exec peer0.org1.example.com peer channel list"
echo ""
echo "# Check peer ledger height:"
echo "docker exec peer0.org1.example.com peer ledger info --channelID voting-channel 2>/dev/null || echo 'Channel not yet created'"

echo -e "\n${YELLOW}[3] Check CouchDB${NC}"
echo "------------------------------------------"
echo "# Check CouchDB databases:"
echo "curl -u admin:adminpw http://localhost:5984/_all_dbs"
echo ""
echo "# Verify voting application database:"
echo "curl -u admin:adminpw http://localhost:5984/peer0_org1_voting 2>/dev/null || echo 'Database not yet created'"

echo -e "\n${YELLOW}[4] Network Topology Verification${NC}"
echo "------------------------------------------"
echo "# The 4-orderer BFT network topology:"
echo "#"
echo "#    ┌─────────────┐     ┌─────────────┐"
echo "#    │  Orderer 1  │─────│  Orderer 2  │"
echo "#    │  (Primary)  │     │  (Replica)  │"
echo "#    └──────┬──────┘     └──────┬──────┘"
echo "#           │                    │"
echo "#    ┌──────┴──────┐     ┌──────┴──────┐"
echo "#    │  Orderer 3  │─────│  Orderer 4  │"
echo "#    │  (Replica)  │     │  (Replica)  │"
echo "#    └─────────────┘     └─────────────┘"
echo "#"
echo "# SmartBFT tolerates f Byzantine faults with 3f+1 nodes"
echo "# 4 nodes = tolerates 1 Byzantine fault"

echo -e "\n${YELLOW}[5] Verify TLS Certificates${NC}"
echo "------------------------------------------"
echo "# Check TLS certificate validity:"
echo "openssl x509 -in ./crypto/orderer1/tls/server.crt -noout -dates"
echo ""
echo "# Verify certificate chain:"
echo "openssl verify -CAfile ./crypto/orderer1/tls/ca.crt ./crypto/orderer1/tls/server.crt"

echo -e "\n${YELLOW}[6] Verify MSP Configuration${NC}"
echo "------------------------------------------"
echo "# Check MSP structure:"
echo "ls -la ./crypto/orderer1/msp/"
echo "ls -la ./crypto/org1/msp/"

echo -e "\n=========================================="
echo "  Verification Complete"
echo "=========================================="
